INSERT INTO ricette(title, ingridients, photo, `time`, portions, description) VALUES('Pane', '500g di farina 00, 350g di acqua, 8g di sale, 7g di lievito di birra', 'https://www.giallozafferano.it/images/176-17692/Pasta-per-il-pane_450x300.jpg', '55 min', 4, 'Pane classico da condividere con gli amici ');
INSERT INTO ricette(title, ingridients, photo, `time`, portions, description) VALUES('Pesto alla genovese', '70g di basilico, 70g di olio extravergine, 50g di Parmiggiano Reggiano DOP, 30g di pecorino, 30g di pinoli, 2 spicchi di aglio, 3g di sale grosso', 'https://www.giallozafferano.it/images/234-23498/Pesto-alla-Genovese_450x300.jpg', '30 min', 4, 'Ricetta classica del pesto alla genovese');
INSERT INTO ricette(title, ingridients, photo, `time`, portions, description) VALUES('Tiramisù', '750g di mascarpone, 260g di uova(circa 5 medie), 250g di savoiardi, 120g di zucchero, 300g di caffè, q.b. di cacao amaro', 'https://www.giallozafferano.it/images/237-23742/Tiramisu_450x300.jpg', '40 min', 8, 'Il classico dolce di chi ama il caffè e non solo ');
INSERT INTO ricette(title, ingridients, photo, `time`, portions, description) VALUES('Polpette', '220g di manzo macinato, 30g di pane raffermo, 165g di salsiccia, 25g di Parmiggiano Reggiano, 1 uovo, q.b. di sale, q.b. di olio, q.b. di pepe', 'https://www.giallozafferano.it/images/242-24200/Polpette-di-carne_450x300.jpg', '20 min', 32, 'Polpette di carne di manzo della tradizione ma veramente buone');
INSERT INTO ricette(title, ingridients, photo, `time`, portions, description) VALUES('Parmigiana di patate', '1kg di patate, 350g di provola, 160g di prosciutto cotto, 100g di Grana Padano, 500g di latte, 50g di burro, 25g di farina 00, q.b. di sale, q.b. di pepe, q.b. di noce moscata', 'https://www.giallozafferano.it/images/229-22972/Parmigiana-di-patate_450x300.jpg', '40 min', 6, 'Come la classica parmigiana di melenzane, ma con le patate');
--categorie
INSERT INTO categories(name) VALUES('Antipasto');
INSERT INTO categories(name) VALUES('Primo Piatto');
INSERT INTO categories(name) VALUES('Secondo Piatto');
INSERT INTO categories(name) VALUES('Contorno');
INSERT INTO categories(name) VALUES('Dessert');